//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
            this.VinculoMenuRecursoes = new HashSet<VinculoMenuRecurso>();
        }
    
        public int Id { get; set; }
        public int IdClaseMenu { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public string Descripcion { get; set; }
        public string Hint { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ClaseMenu ClaseMenu { get; set; }
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
        public virtual ICollection<VinculoMenuRecurso> VinculoMenuRecursoes { get; set; }
    }
}
