//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienesSustraidosAnimal
    {
        public int id { get; set; }
        public int idNNBienSustraido { get; set; }
        public int idClaseGanado { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string idUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual BienesSustraido BienesSustraido { get; set; }
        public virtual NNClaseGanado NNClaseGanado { get; set; }
    }
}
