//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    
    public partial class DelitosAutoresAnalisisGeneral_Result
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> idDelito { get; set; }
        public string idCausa { get; set; }
        public string edadAproximada { get; set; }
        public string sexo { get; set; }
        public string estatura { get; set; }
        public string robustez { get; set; }
        public string colorPiel { get; set; }
        public string colorOjos { get; set; }
        public string colorCabello { get; set; }
        public string tipoCabello { get; set; }
        public string calvicie { get; set; }
        public string formaCara { get; set; }
        public string dimesionCeja { get; set; }
        public string tipoCeja { get; set; }
        public string formaMenton { get; set; }
        public string formaOreja { get; set; }
        public string formaNariz { get; set; }
        public string formaBoca { get; set; }
        public string labioInferior { get; set; }
        public string labioSuperior { get; set; }
        public string idSic { get; set; }
        public string claseRostro { get; set; }
        public string CubiertoCon { get; set; }
        public string idImputadoSimp { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string OtraCaracteristica { get; set; }
        public string apellido { get; set; }
        public string nombres { get; set; }
        public string apodo { get; set; }
        public Nullable<int> dni { get; set; }
        public Nullable<int> CoincidenciaFormaLabioSup { get; set; }
        public Nullable<int> CoincidenciaFormaLabioInf { get; set; }
        public Nullable<int> CoincidenciaFormaBoca { get; set; }
        public Nullable<int> CoincidenciaFormaNariz { get; set; }
        public Nullable<int> CoincidenciaFormaOreja { get; set; }
        public Nullable<int> CoincidenciaFormaMenton { get; set; }
        public Nullable<int> CoincidenciaTipoCeja { get; set; }
        public Nullable<int> CoincidenciaDimensionCeja { get; set; }
        public Nullable<int> CoincidenciaFormaCara { get; set; }
        public Nullable<int> CoincidenciaTipoCabello { get; set; }
        public Nullable<int> CoincidenciaColorCabello { get; set; }
        public Nullable<int> CoincidenciaClaseCalvicie { get; set; }
        public Nullable<int> CoincidenciaColorOjos { get; set; }
        public Nullable<int> CoincidenciaColorPiel { get; set; }
        public Nullable<int> CoincidenciaRobustez { get; set; }
        public Nullable<int> CoincidenciaEstatura { get; set; }
        public Nullable<int> CoincidenciaEdad { get; set; }
        public Nullable<int> CoincidenciaClaseRostro { get; set; }
        public Nullable<int> CoincidenciaSeniasParticulares { get; set; }
        public Nullable<int> CoincidenciaTatuajes { get; set; }
        public Nullable<int> CoincidenciaApellido { get; set; }
        public Nullable<int> CoincidenciaNombre { get; set; }
        public Nullable<int> CoincidenciaApodo { get; set; }
        public Nullable<int> CoincidenciaDNI { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public string IgnoradoAp { get; set; }
    }
}
