//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerCapturer.ServiceCapturaDecaDactilar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImputadoDatosPers", Namespace="http://schemas.datacontract.org/2004/07/ISIC.Services")]
    [System.SerializableAttribute()]
    public partial class ImputadoDatosPers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AccesoRenaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoBarrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoRenaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreRenaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AccesoRenaper {
            get {
                return this.AccesoRenaperField;
            }
            set {
                if ((this.AccesoRenaperField.Equals(value) != true)) {
                    this.AccesoRenaperField = value;
                    this.RaisePropertyChanged("AccesoRenaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoBarras {
            get {
                return this.CodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoBarrasField, value) != true)) {
                    this.CodigoBarrasField = value;
                    this.RaisePropertyChanged("CodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((this.DNIField.Equals(value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPP {
            get {
                return this.IPPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPPField, value) != true)) {
                    this.IPPField = value;
                    this.RaisePropertyChanged("IPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultadoRenaper {
            get {
                return this.ResultadoRenaperField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoRenaperField, value) != true)) {
                    this.ResultadoRenaperField = value;
                    this.RaisePropertyChanged("ResultadoRenaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScoreRenaper {
            get {
                return this.ScoreRenaperField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreRenaperField, value) != true)) {
                    this.ScoreRenaperField = value;
                    this.RaisePropertyChanged("ScoreRenaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HuellasImputado", Namespace="http://schemas.datacontract.org/2004/07/ISIC.Services")]
    [System.SerializableAttribute()]
    public partial class HuellasImputado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FingerCapturer.ServiceCapturaDecaDactilar.Dedos[] DedosCapturadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FingerCapturer.ServiceCapturaDecaDactilar.Dedos[] DedosFaltantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TemplateSujetoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FingerCapturer.ServiceCapturaDecaDactilar.Dedos[] DedosCapturados {
            get {
                return this.DedosCapturadosField;
            }
            set {
                if ((object.ReferenceEquals(this.DedosCapturadosField, value) != true)) {
                    this.DedosCapturadosField = value;
                    this.RaisePropertyChanged("DedosCapturados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FingerCapturer.ServiceCapturaDecaDactilar.Dedos[] DedosFaltantes {
            get {
                return this.DedosFaltantesField;
            }
            set {
                if ((object.ReferenceEquals(this.DedosFaltantesField, value) != true)) {
                    this.DedosFaltantesField = value;
                    this.RaisePropertyChanged("DedosFaltantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] TemplateSujeto {
            get {
                return this.TemplateSujetoField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateSujetoField, value) != true)) {
                    this.TemplateSujetoField = value;
                    this.RaisePropertyChanged("TemplateSujeto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dedos", Namespace="http://schemas.datacontract.org/2004/07/ISIC.Services")]
    [System.SerializableAttribute()]
    public partial class Dedos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Neurotec.Biometrics.NFPosition PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Neurotec.Biometrics.NFPosition Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCapturaDecaDactilar.ICapturaDecaDactilarService")]
    public interface ICapturaDecaDactilarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapturaDecaDactilarService/CapturaHuellasCliente", ReplyAction="http://tempuri.org/ICapturaDecaDactilarService/CapturaHuellasClienteResponse")]
        int CapturaHuellasCliente(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICapturaDecaDactilarService/CapturaHuellasCliente", ReplyAction="http://tempuri.org/ICapturaDecaDactilarService/CapturaHuellasClienteResponse")]
        System.IAsyncResult BeginCapturaHuellasCliente(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto, System.AsyncCallback callback, object asyncState);
        
        int EndCapturaHuellasCliente(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICapturaDecaDactilarServiceChannel : FingerCapturer.ServiceCapturaDecaDactilar.ICapturaDecaDactilarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CapturaHuellasClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CapturaHuellasClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CapturaDecaDactilarServiceClient : System.ServiceModel.ClientBase<FingerCapturer.ServiceCapturaDecaDactilar.ICapturaDecaDactilarService>, FingerCapturer.ServiceCapturaDecaDactilar.ICapturaDecaDactilarService {
        
        private BeginOperationDelegate onBeginCapturaHuellasClienteDelegate;
        
        private EndOperationDelegate onEndCapturaHuellasClienteDelegate;
        
        private System.Threading.SendOrPostCallback onCapturaHuellasClienteCompletedDelegate;
        
        public CapturaDecaDactilarServiceClient() {
        }
        
        public CapturaDecaDactilarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CapturaDecaDactilarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapturaDecaDactilarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapturaDecaDactilarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CapturaHuellasClienteCompletedEventArgs> CapturaHuellasClienteCompleted;
        
        public int CapturaHuellasCliente(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto) {
            return base.Channel.CapturaHuellasCliente(imputado, sujeto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCapturaHuellasCliente(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCapturaHuellasCliente(imputado, sujeto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndCapturaHuellasCliente(System.IAsyncResult result) {
            return base.Channel.EndCapturaHuellasCliente(result);
        }
        
        private System.IAsyncResult OnBeginCapturaHuellasCliente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado = ((FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers)(inValues[0]));
            FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto = ((FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado)(inValues[1]));
            return this.BeginCapturaHuellasCliente(imputado, sujeto, callback, asyncState);
        }
        
        private object[] OnEndCapturaHuellasCliente(System.IAsyncResult result) {
            int retVal = this.EndCapturaHuellasCliente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCapturaHuellasClienteCompleted(object state) {
            if ((this.CapturaHuellasClienteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CapturaHuellasClienteCompleted(this, new CapturaHuellasClienteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CapturaHuellasClienteAsync(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto) {
            this.CapturaHuellasClienteAsync(imputado, sujeto, null);
        }
        
        public void CapturaHuellasClienteAsync(FingerCapturer.ServiceCapturaDecaDactilar.ImputadoDatosPers imputado, FingerCapturer.ServiceCapturaDecaDactilar.HuellasImputado sujeto, object userState) {
            if ((this.onBeginCapturaHuellasClienteDelegate == null)) {
                this.onBeginCapturaHuellasClienteDelegate = new BeginOperationDelegate(this.OnBeginCapturaHuellasCliente);
            }
            if ((this.onEndCapturaHuellasClienteDelegate == null)) {
                this.onEndCapturaHuellasClienteDelegate = new EndOperationDelegate(this.OnEndCapturaHuellasCliente);
            }
            if ((this.onCapturaHuellasClienteCompletedDelegate == null)) {
                this.onCapturaHuellasClienteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCapturaHuellasClienteCompleted);
            }
            base.InvokeAsync(this.onBeginCapturaHuellasClienteDelegate, new object[] {
                        imputado,
                        sujeto}, this.onEndCapturaHuellasClienteDelegate, this.onCapturaHuellasClienteCompletedDelegate, userState);
        }
    }
}
