//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audita
    {
        public int Id { get; set; }
        public string usuario { get; set; }
        public string IPAddress { get; set; }
        public string AreaAccedida { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> nivel { get; set; }
        public string Data { get; set; }
    }
}
