//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaseTatuaje
    {
        public ClaseTatuaje()
        {
            this.BusquedaRobosDelitosSexualesTatuajes = new HashSet<BusquedaRobosDelitosSexualesTatuaje>();
            this.TatuajesPersonas = new HashSet<TatuajesPersonas>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<BusquedaRobosDelitosSexualesTatuaje> BusquedaRobosDelitosSexualesTatuajes { get; set; }
        public virtual ICollection<TatuajesPersonas> TatuajesPersonas { get; set; }
    }
}
