//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comisaria
    {
        public Comisaria()
        {
            this.Busquedas = new HashSet<Busqueda>();
            this.Delitos = new HashSet<Delito>();
            this.Delitos1 = new HashSet<Delito>();
            this.PersonasDesaparecidas = new HashSet<PersonasDesaparecidas>();
            this.PersonasHalladas = new HashSet<PersonasHalladas>();
        }
    
        public int id { get; set; }
        public string Comisaria1 { get; set; }
        public int idDepartamento { get; set; }
    
        public virtual ICollection<Busqueda> Busquedas { get; set; }
        public virtual ICollection<Delito> Delitos { get; set; }
        public virtual ICollection<Delito> Delitos1 { get; set; }
        public virtual ICollection<PersonasDesaparecidas> PersonasDesaparecidas { get; set; }
        public virtual ICollection<PersonasHalladas> PersonasHalladas { get; set; }
    }
}
