//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.Delitos = new HashSet<Delito>();
            this.Delitos1 = new HashSet<Delito>();
            this.Localidads = new HashSet<Localidad>();
            this.PuntoGestions = new HashSet<PuntoGestion>();
        }
    
        public int id { get; set; }
        public string Partido1 { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public int idProvincia { get; set; }
    
        public virtual ICollection<Delito> Delitos { get; set; }
        public virtual ICollection<Delito> Delitos1 { get; set; }
        public virtual ICollection<Localidad> Localidads { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<PuntoGestion> PuntoGestions { get; set; }
    }
}
