//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.PermisoGrupoes = new HashSet<PermisoGrupo>();
            this.PermisoUsuarios = new HashSet<PermisoUsuario>();
            this.VinculoMenuRecursoes = new HashSet<VinculoMenuRecurso>();
        }
    
        public string id { get; set; }
        public string Descripcion { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<PermisoGrupo> PermisoGrupoes { get; set; }
        public virtual ICollection<PermisoUsuario> PermisoUsuarios { get; set; }
        public virtual ICollection<VinculoMenuRecurso> VinculoMenuRecursoes { get; set; }
    }
}
