//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VinculoMenuRecurso
    {
        public string Id { get; set; }
        public int IdMenu { get; set; }
        public string IdRecurso { get; set; }
        public Nullable<int> PermisoRecurso { get; set; }
        public string Url { get; set; }
        public string Criterio { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
