//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalPoderJudicial
    {
        public PersonalPoderJudicial()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public string id { get; set; }
        public int idPersona { get; set; }
        public int idJerarquia { get; set; }
        public string idPuntoGestion { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> Instruye { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual PuntoGestion PuntoGestion { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
