//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int id { get; set; }
        public Nullable<int> idBienSustraido { get; set; }
        public int idDelito { get; set; }
        public string idCausa { get; set; }
        public Nullable<int> idClaseVinculoVehiculo { get; set; }
        public Nullable<int> idMarcaVehiculo { get; set; }
        public Nullable<int> idModeloVehiculo { get; set; }
        public string Dominio { get; set; }
        public string NumeroChasis { get; set; }
        public string NumeroMotor { get; set; }
        public Nullable<int> idColorVehiculo { get; set; }
        public string anio { get; set; }
        public Nullable<int> GNC { get; set; }
        public string IdentificacionGNC { get; set; }
        public Nullable<int> idClaseVidrioVehiculo { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string idUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual BienesSustraido BienesSustraido { get; set; }
        public virtual ColorVehiculo ColorVehiculo { get; set; }
        public virtual Delito Delito { get; set; }
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual ModeloVehiculo ModeloVehiculo { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean { get; set; }
        public virtual NNClaseVidrioVehiculo NNClaseVidrioVehiculo { get; set; }
        public virtual NNClaseVinculoVehiculo NNClaseVinculoVehiculo { get; set; }
    }
}
