//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeniasParticulares
    {
        public int id { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idSeniaParticular { get; set; }
        public Nullable<int> idUbicacionSeniaParticular { get; set; }
        public Nullable<int> idTablaDestino { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idAutor { get; set; }
    
        public virtual Autores Autore { get; set; }
        public virtual ClaseSeniaParticular ClaseSeniaParticular { get; set; }
        public virtual ClaseTipoPersona ClaseTipoPersona { get; set; }
        public virtual ClaseUbicacionSeniaPart ClaseUbicacionSeniaPart { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
