//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busqueda
    {
        public Busqueda()
        {
            this.BusquedaAspectoCabelloes = new HashSet<BusquedaAspectoCabello>();
            this.BusquedaCalvicies = new HashSet<BusquedaCalvicie>();
            this.BusquedaColorCabelloes = new HashSet<BusquedaColorCabello>();
            this.BusquedaColorOjos = new HashSet<BusquedaColorOjo>();
            this.BusquedaColorPiels = new HashSet<BusquedaColorPiel>();
            this.BusquedaColorTenidoes = new HashSet<BusquedaColorTenido>();
            this.BusquedaGrupoSanguineos = new HashSet<BusquedaGrupoSanguineo>();
            this.BusquedaLongitudCabelloes = new HashSet<BusquedaLongitudCabello>();
            this.BusquedaRostroes = new HashSet<BusquedaRostro>();
            this.BusquedaSeniasParticulares = new HashSet<BusquedaSeniasParticulare>();
            this.BusquedaTatuajes = new HashSet<BusquedaTatuaje>();
        }
    
        public int Id { get; set; }
        public string UFI { get; set; }
        public Nullable<int> idOrigen { get; set; }
        public string Usuario { get; set; }
        public string TablaDestino { get; set; }
        public string DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<int> EdadDesde { get; set; }
        public Nullable<int> EdadHasta { get; set; }
        public Nullable<int> idsexo { get; set; }
        public Nullable<float> TallaDesde { get; set; }
        public Nullable<float> TallaHasta { get; set; }
        public Nullable<float> PesoDesde { get; set; }
        public Nullable<float> PesoHasta { get; set; }
        public Nullable<int> FaltanPiezasDentales { get; set; }
        public string CodigoADN { get; set; }
        public Nullable<int> CantidadCoincidencias { get; set; }
        public Nullable<System.DateTime> FechaUltimaCoincidencia { get; set; }
        public Nullable<int> idComisariaIntervinoAparcicion { get; set; }
        public Nullable<System.DateTime> fechaActuaciones { get; set; }
        public Nullable<int> idMotivoHallazgo { get; set; }
        public string MotivoHallazgoDescripcion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string IPP { get; set; }
        public Nullable<int> TieneADN { get; set; }
    
        public virtual Comisaria Comisaria { get; set; }
        public virtual PBClaseBoolean PBClaseBoolean { get; set; }
        public virtual PBClaseMotivoHallazgo PBClaseMotivoHallazgo { get; set; }
        public virtual PBClaseSexo PBClaseSexo { get; set; }
        public virtual PBClaseTablaDestino PBClaseTablaDestino { get; set; }
        public virtual ICollection<BusquedaAspectoCabello> BusquedaAspectoCabelloes { get; set; }
        public virtual ICollection<BusquedaCalvicie> BusquedaCalvicies { get; set; }
        public virtual ICollection<BusquedaColorCabello> BusquedaColorCabelloes { get; set; }
        public virtual ICollection<BusquedaColorOjo> BusquedaColorOjos { get; set; }
        public virtual ICollection<BusquedaColorPiel> BusquedaColorPiels { get; set; }
        public virtual ICollection<BusquedaColorTenido> BusquedaColorTenidoes { get; set; }
        public virtual ICollection<BusquedaGrupoSanguineo> BusquedaGrupoSanguineos { get; set; }
        public virtual ICollection<BusquedaLongitudCabello> BusquedaLongitudCabelloes { get; set; }
        public virtual ICollection<BusquedaRostro> BusquedaRostroes { get; set; }
        public virtual ICollection<BusquedaSeniasParticulare> BusquedaSeniasParticulares { get; set; }
        public virtual ICollection<BusquedaTatuaje> BusquedaTatuajes { get; set; }
    }
}
