//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Text;
using MPBA.SIAC.Web.Models;
using System.ComponentModel.DataAnnotations;
namespace MPBA.SIAC.Web.Models
{
   public class PBFotosDatosPersonales
    {
         
      /*  public List<String> fotosString{ get; set; }*/
        public List<PBFotos> pbFotos { get; set; }
        public int IdPersona { get; set; }
        public string Ipp { get; set; }
        public string DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }

         }
    
}
