//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delito
    {
        public Delito()
        {
            this.Autores = new HashSet<Autores>();
            this.BienesSustraidos = new HashSet<BienesSustraido>();
            this.LugaresDeTrasladoDeVictimas = new HashSet<LugaresDeTrasladoDeVictima>();
            this.Rastros = new HashSet<Rastro>();
            this.Vehiculos = new HashSet<Vehiculo>();
        }
    
        public int id { get; set; }
        public string idCausa { get; set; }
        public int idClaseDelito { get; set; }
        public Nullable<int> idClaseFecha { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<int> idClaseHora { get; set; }
        public string HoraDesde { get; set; }
        public string HoraHasta { get; set; }
        public Nullable<int> idClaseMomentoDelDia { get; set; }
        public Nullable<int> idPartido { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public Nullable<int> idCalle { get; set; }
        public string idOtraCalle { get; set; }
        public Nullable<int> idEntreCalle1 { get; set; }
        public string idOtraEntreCalle { get; set; }
        public Nullable<int> idEntreCalle2 { get; set; }
        public string idOtraEntreCalle2 { get; set; }
        public string NroH { get; set; }
        public string PisoH { get; set; }
        public string DeptoH { get; set; }
        public string ParajeBarrioH { get; set; }
        public Nullable<int> idComisariaH { get; set; }
        public Nullable<int> idClaseLugar { get; set; }
        public Nullable<int> idClaseRubro { get; set; }
        public string NomRefLugarRubro { get; set; }
        public Nullable<int> idClaseModoArriboHuida { get; set; }
        public Nullable<int> idClaseModusOperandis { get; set; }
        public string ExprUtilizadaComienzoDelHecho { get; set; }
        public string ExprReiteradaDuranteHecho { get; set; }
        public string IngresaronPor { get; set; }
        public Nullable<int> VictimasEnElLugar { get; set; }
        public Nullable<int> UsoDeArmas { get; set; }
        public Nullable<int> idClaseArma { get; set; }
        public Nullable<short> idClaseSubtipoArma { get; set; }
        public string OtraClaseArma { get; set; }
        public Nullable<int> HuboAgresionFisicaAVictima { get; set; }
        public Nullable<int> idClaseAgresion { get; set; }
        public Nullable<int> idClaseZonaCuerpoLesionada { get; set; }
        public Nullable<int> VictimaTrasladadaAOtroLugar { get; set; }
        public Nullable<int> idPartidoL { get; set; }
        public Nullable<int> idLocalidadL { get; set; }
        public Nullable<int> idCalleL { get; set; }
        public string idOtraCalleL { get; set; }
        public Nullable<int> idEntreCalle1L { get; set; }
        public string OtraEntreCalle1L { get; set; }
        public Nullable<int> idEntreCalle2L { get; set; }
        public string OtraEntreCalle2L { get; set; }
        public string ParajeBarrioL { get; set; }
        public Nullable<int> idComisariaL { get; set; }
        public Nullable<int> idClaseCantidadAutores { get; set; }
        public Nullable<float> MontoTotalEstimadoBienSustraido { get; set; }
        public Nullable<int> idVicTestRecRueda { get; set; }
        public Nullable<int> idClaseCantAutorReconocidos { get; set; }
        public Nullable<int> idClaseCondicionVictima { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string idUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> idTipoAutor { get; set; }
        public string idUsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string MotivoBaja { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual ICollection<Autores> Autores { get; set; }
        public virtual ICollection<BienesSustraido> BienesSustraidos { get; set; }
        public virtual Comisaria Comisaria { get; set; }
        public virtual Comisaria Comisaria1 { get; set; }
        public virtual NNClaseAgresion NNClaseAgresion { get; set; }
        public virtual NNClaseArma NNClaseArma { get; set; }
        public virtual NNClaseCantAutorReconocido NNClaseCantAutorReconocido { get; set; }
        public virtual NNClaseCantidadAutore NNClaseCantidadAutore { get; set; }
        public virtual NNClaseFecha NNClaseFecha { get; set; }
        public virtual NNClaseHora NNClaseHora { get; set; }
        public virtual NNClaseLugar NNClaseLugar { get; set; }
        public virtual NNClaseModoArriboHuida NNClaseModoArriboHuida { get; set; }
        public virtual NNClaseModusOperandi NNClaseModusOperandi { get; set; }
        public virtual NNClaseMomentoDia NNClaseMomentoDia { get; set; }
        public virtual NNClaseRubro NNClaseRubro { get; set; }
        public virtual NNClaseZonaCuerpoLesionada NNClaseZonaCuerpoLesionada { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean1 { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean2 { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean3 { get; set; }
        public virtual NNClaseBoolean NNClaseBoolean4 { get; set; }
        public virtual NNClaseCondicionVictima NNClaseCondicionVictima { get; set; }
        public virtual NNClaseSubtipoArma NNClaseSubtipoArma { get; set; }
        public virtual NNClaseTipoDelito NNClaseTipoDelito { get; set; }
        public virtual Partido Partido { get; set; }
        public virtual Partido Partido1 { get; set; }
        public virtual ICollection<LugaresDeTrasladoDeVictima> LugaresDeTrasladoDeVictimas { get; set; }
        public virtual ICollection<Rastro> Rastros { get; set; }
        public virtual ICollection<Vehiculo> Vehiculos { get; set; }
    }
}
