//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.PermisoUsuarios = new HashSet<PermisoUsuario>();
            this.Personas = new HashSet<Persona>();
        }
    
        public string id { get; set; }
        public string idPersonalPoderJudicial { get; set; }
        public string NombreUsuario { get; set; }
        public string ClaveUsuario { get; set; }
        public string idGrupoUsuario { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> Actividad { get; set; }
        public string version { get; set; }
        public Nullable<bool> bitacoraMemoria { get; set; }
        public Nullable<short> MargenArriba { get; set; }
        public Nullable<short> MargenIzquierda { get; set; }
        public Nullable<short> MargenAbajo { get; set; }
        public Nullable<short> MargenDerecha { get; set; }
        public Nullable<bool> EsReferenteTrata { get; set; }
    
        public virtual GrupoUsuario GrupoUsuario { get; set; }
        public virtual ICollection<PermisoUsuario> PermisoUsuarios { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual PersonalPoderJudicial PersonalPoderJudicial { get; set; }
    }
}
