//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diente
    {
        public int Id { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idDiente { get; set; }
        public Nullable<bool> Existe { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
        public Nullable<bool> Baja { get; set; }
    }
}
