//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaseEstadoCivil
    {
        public ClaseEstadoCivil()
        {
            this.Personas = new HashSet<Persona>();
            this.Personas1 = new HashSet<Persona>();
            this.Personas2 = new HashSet<Persona>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<Persona> Personas1 { get; set; }
        public virtual ICollection<Persona> Personas2 { get; set; }
    }
}
