//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailsAsociadosPersonasBuscada
    {
        public int idPersonaBuscada { get; set; }
        public int idTipoPersona { get; set; }
        public string Mail { get; set; }
        public bool seleccionado { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int id { get; set; }
    }
}
