//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasHalladas
    {
        public int Id { get; set; }
        public string Ipp { get; set; }
        public string UFI { get; set; }
        public string DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> idOrganismoInterviniente { get; set; }
        public Nullable<int> idComisaria { get; set; }
        public Nullable<int> idLugarHallazgo { get; set; }
        public Nullable<System.DateTime> FechaHallazgo { get; set; }
        public Nullable<int> idSexo { get; set; }
        public Nullable<int> EdadAparente { get; set; }
        public Nullable<int> EdadCientifica { get; set; }
        public Nullable<float> Talla { get; set; }
        public Nullable<float> Peso { get; set; }
        public Nullable<int> idColorPiel { get; set; }
        public Nullable<int> idColorCabello { get; set; }
        public Nullable<int> idColorTenido { get; set; }
        public Nullable<int> idLongitudCabello { get; set; }
        public Nullable<int> idAspectoCabello { get; set; }
        public Nullable<int> idCalvicie { get; set; }
        public Nullable<int> idColorOjos { get; set; }
        public Nullable<int> idRostro { get; set; }
        public Nullable<int> CantidadDiasNoAfeitado { get; set; }
        public Nullable<int> FaltanPiezasDentales { get; set; }
        public Nullable<int> idDentadura { get; set; }
        public Nullable<int> tieneADN { get; set; }
        public string ADN { get; set; }
        public Nullable<int> idGrupoSanguineo { get; set; }
        public Nullable<int> Foto { get; set; }
        public Nullable<int> FichasDactilares { get; set; }
        public string Ropa { get; set; }
        public string ArticulosPersonales { get; set; }
        public Nullable<int> ExistenRadiografia { get; set; }
        public Nullable<int> Vive { get; set; }
        public Nullable<int> idBusqueda { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool esExtJurisdiccion { get; set; }
        public bool RestosOseos { get; set; }
        public Nullable<int> MotivoDeBaja { get; set; }
        public Nullable<System.DateTime> FechaDeBaja { get; set; }
        public Nullable<int> idTipoDNI { get; set; }
    
        public virtual Comisaria Comisaria { get; set; }
        public virtual PBClaseAspectoCabello PBClaseAspectoCabello { get; set; }
        public virtual PBClaseBoolean PBClaseBoolean { get; set; }
        public virtual PBClaseBoolean PBClaseBoolean1 { get; set; }
        public virtual PBClaseBoolean PBClaseBoolean2 { get; set; }
        public virtual PBClaseCalvicie PBClaseCalvicie { get; set; }
        public virtual PBClaseColor PBClaseColor { get; set; }
        public virtual PBClaseColorCabello PBClaseColorCabello { get; set; }
        public virtual PBClaseColorDePiel PBClaseColorDePiel { get; set; }
        public virtual PBClaseColorOjos PBClaseColorOjo { get; set; }
        public virtual PBClaseGrupoSanguineo PBClaseGrupoSanguineo { get; set; }
        public virtual PBClaseLongitudCabello PBClaseLongitudCabello { get; set; }
        public virtual PBClaseOrganismoInterviniente PBClaseOrganismoInterviniente { get; set; }
        public virtual PBClaseRostro PBClaseRostro { get; set; }
        public virtual PBClaseSexo PBClaseSexo { get; set; }
    }
}
