//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerCapturer.IdentityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenaperIdentityRequest", Namespace="http://schemas.datacontract.org/2004/07/ISIC.Services")]
    [System.SerializableAttribute()]
    public partial class RenaperIdentityRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripsionH1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripsionH2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenH1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenH2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((this.DNIField.Equals(value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripsionH1 {
            get {
                return this.DescripsionH1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DescripsionH1Field, value) != true)) {
                    this.DescripsionH1Field = value;
                    this.RaisePropertyChanged("DescripsionH1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripsionH2 {
            get {
                return this.DescripsionH2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DescripsionH2Field, value) != true)) {
                    this.DescripsionH2Field = value;
                    this.RaisePropertyChanged("DescripsionH2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenH1 {
            get {
                return this.ImagenH1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenH1Field, value) != true)) {
                    this.ImagenH1Field = value;
                    this.RaisePropertyChanged("ImagenH1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenH2 {
            get {
                return this.ImagenH2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenH2Field, value) != true)) {
                    this.ImagenH2Field = value;
                    this.RaisePropertyChanged("ImagenH2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdentityService.IRenaperIdentityService")]
    public interface IRenaperIdentityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaperIdentityService/VerifyIdentity", ReplyAction="http://tempuri.org/IRenaperIdentityService/VerifyIdentityResponse")]
        string VerifyIdentity(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRenaperIdentityService/VerifyIdentity", ReplyAction="http://tempuri.org/IRenaperIdentityService/VerifyIdentityResponse")]
        System.IAsyncResult BeginVerifyIdentity(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest, System.AsyncCallback callback, object asyncState);
        
        string EndVerifyIdentity(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRenaperIdentityServiceChannel : FingerCapturer.IdentityService.IRenaperIdentityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VerifyIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RenaperIdentityServiceClient : System.ServiceModel.ClientBase<FingerCapturer.IdentityService.IRenaperIdentityService>, FingerCapturer.IdentityService.IRenaperIdentityService {
        
        private BeginOperationDelegate onBeginVerifyIdentityDelegate;
        
        private EndOperationDelegate onEndVerifyIdentityDelegate;
        
        private System.Threading.SendOrPostCallback onVerifyIdentityCompletedDelegate;
        
        public RenaperIdentityServiceClient() {
        }
        
        public RenaperIdentityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RenaperIdentityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenaperIdentityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenaperIdentityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<VerifyIdentityCompletedEventArgs> VerifyIdentityCompleted;
        
        public string VerifyIdentity(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest) {
            return base.Channel.VerifyIdentity(renaperIdentityRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVerifyIdentity(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVerifyIdentity(renaperIdentityRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndVerifyIdentity(System.IAsyncResult result) {
            return base.Channel.EndVerifyIdentity(result);
        }
        
        private System.IAsyncResult OnBeginVerifyIdentity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest = ((FingerCapturer.IdentityService.RenaperIdentityRequest)(inValues[0]));
            return this.BeginVerifyIdentity(renaperIdentityRequest, callback, asyncState);
        }
        
        private object[] OnEndVerifyIdentity(System.IAsyncResult result) {
            string retVal = this.EndVerifyIdentity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVerifyIdentityCompleted(object state) {
            if ((this.VerifyIdentityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VerifyIdentityCompleted(this, new VerifyIdentityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VerifyIdentityAsync(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest) {
            this.VerifyIdentityAsync(renaperIdentityRequest, null);
        }
        
        public void VerifyIdentityAsync(FingerCapturer.IdentityService.RenaperIdentityRequest renaperIdentityRequest, object userState) {
            if ((this.onBeginVerifyIdentityDelegate == null)) {
                this.onBeginVerifyIdentityDelegate = new BeginOperationDelegate(this.OnBeginVerifyIdentity);
            }
            if ((this.onEndVerifyIdentityDelegate == null)) {
                this.onEndVerifyIdentityDelegate = new EndOperationDelegate(this.OnEndVerifyIdentity);
            }
            if ((this.onVerifyIdentityCompletedDelegate == null)) {
                this.onVerifyIdentityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVerifyIdentityCompleted);
            }
            base.InvokeAsync(this.onBeginVerifyIdentityDelegate, new object[] {
                        renaperIdentityRequest}, this.onEndVerifyIdentityDelegate, this.onVerifyIdentityCompletedDelegate, userState);
        }
    }
}
