//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoUsuario
    {
        public GrupoUsuario()
        {
            this.PermisoGrupoes = new HashSet<PermisoGrupo>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public string id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<PermisoGrupo> PermisoGrupoes { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
