//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPBA.SIAC.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoGestion
    {
        public PuntoGestion()
        {
            this.PersonalPoderJudicials = new HashSet<PersonalPoderJudicial>();
            this.PuntoGestion1 = new HashSet<PuntoGestion>();
        }
    
        public string id { get; set; }
        public string idClasePuntoGestion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<bool> Externo { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public int idDepartamento { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public Nullable<int> idPartido { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string DescripcionCorta { get; set; }
        public Nullable<int> OrdenMuestra { get; set; }
        public string titular { get; set; }
        public Nullable<int> idDescentralizada { get; set; }
        public bool activo { get; set; }
        public string Email { get; set; }
        public string idPadrePG { get; set; }
        public string IdTitular { get; set; }
        public string codi_Corte { get; set; }
        public Nullable<short> area_Corte { get; set; }
        public Nullable<int> idClaseMarca { get; set; }
    
        public virtual ClasePuntoGestion ClasePuntoGestion { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Paises Pai { get; set; }
        public virtual Partido Partido { get; set; }
        public virtual ICollection<PersonalPoderJudicial> PersonalPoderJudicials { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<PuntoGestion> PuntoGestion1 { get; set; }
        public virtual PuntoGestion PuntoGestion2 { get; set; }
    }
}
